# BACKGROUND
background {
    monitor =
    path = /home/albetnv/.config/hypr/walls/1.jpg
    # Increased blur to make the text and pill elements pop nicely
    blur_passes = 2
    contrast = 1
    brightness = 0.5
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}

# GENERAL
general {
    hide_cursor = true
    grace = 0
    ignore_empty_input = true
    fail_timeout = 2000 # milliseconds before fail_text and fail_color disappears
}

# TIME
label {
    monitor = 
    text = cmd[update:1000] date +"%-I:%M"
    # Matches waybar clock background #cba6f7
    color = rgb(203, 166, 247)
    font_size = 120
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, 150
    halign = center
    valign = center
    # Simulates waybar clock's box-shadow
    shadow_passes = 2
    shadow_size = 8
    shadow_color = rgba(203, 166, 247, 0.4)
}

# DATE
label {
    monitor =
    text = cmd[update:1000] date +"%A, %B %d"
    # Matches waybar textual #cdd6f4
    color = rgb(205, 214, 244)
    font_size = 25
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 25
    halign = center
    valign = center
    shadow_passes = 1
    shadow_size = 4
    shadow_color = rgba(30, 30, 46, 0.8)
}

# USER
label {
    monitor =
    text = Hi there, <span text_transform="capitalize">$USER</span>
    # Matches waybar workspace highlighted state #89b4fa
    color = rgb(137, 180, 250)
    font_size = 20
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, -40
    halign = center
    valign = center
    shadow_passes = 1
    shadow_size = 4
    shadow_color = rgba(30, 30, 46, 0.8)
}

# INPUT FIELD
input-field {
    monitor =
    size = 280, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true
    
    # Matches waybar workspace background #313244
    outer_color = rgb(49, 50, 68)
    # Matches waybar primary background rgba(30, 30, 46, 0.85)
    inner_color = rgba(30, 30, 46, 0.85)
    
    font_color = rgb(205, 214, 244)
    fade_on_empty = false

    
    # Matches the pill-shaped 20px border radius from waybar modules
    rounding = 20
    
    placeholder_text = <span foreground="##cdd6f4"><i>Enter Password...</i></span>
    hide_input = false
    position = 0, -110
    halign = center
    valign = center
    
    # Matches waybar.css specific element colors
    check_color = rgb(137, 180, 250) # 89b4fa (workspace focused)
    fail_color = rgb(243, 139, 168)  # f38ba8 (workspace urgent / battery critical)
    fail_text = <b>$ATTEMPTS</b>
}
